
#ifndef SSYBC_INCLUDE_SSYBC_CONFIG_SSYBC_CONFIG_HPP_
#define SSYBC_INCLUDE_SSYBC_CONFIG_SSYBC_CONFIG_HPP_


#define SSYBC_VERSION_MAJOR 0
#define SSYBC_VERSION_MINOR 1
#define SSYBC_VERSION_BUILD 1

/* #undef SSYBC_IS_CUDA_ENABLED */

#endif  // SSYBC_INCLUDE_SSYBC_CONFIG_SSYBC_CONFIG_HPP_
